#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/config/bootstrap.php';

use Symfony\Component\Console\Application;

use Elagiou\VacationPortal\Commands\RunTablesCommand;
use Elagiou\VacationPortal\Commands\SeedCommand;
use Elagiou\VacationPortal\Commands\ServeCommand;

$app = new Application('Vacation Portal CLI', '1.0.0');

// Register commands
$app->add((new RunTablesCommand())->setName('db:migrate'));
$app->add(new ServeCommand())->setName('serve');
$app->add((new SeedCommand())->setName('db:seed'));

$app->run();
