#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/config/bootstrap.php';

use Symfony\Component\Console\Application;
use Elagiou\VacationPortal\Commands\{
    RunTablesCommand,
    ServeCommand
};

$app = new Application('Vacation Portal CLI', '1.0.0');

// ✅ Set names BEFORE adding them to the Application
$app->add((new RunTablesCommand())->setName('db'));
$app->add((new ServeCommand())->setName('serve'));

$app->run();
